# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85bb5f141a7c56bbf97f68b6020a63c6e3505ec579d7ff65be470e927cf61ab35f4683e832e52b9932d2a11ebbf1a2e8e43003232dce3a1ba347f6e8422ec989

test:
  secret_key_base: fb008427ee2a738910ebf6361da9bdf30dc20d383189f3c4d8eb517d6819871ebb1c5d0bed03a96c99e914ce8f0c6f2ae773340c5d7986eb4e7c2e39fa800caf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
